# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24130b97900221ea9f32ddb832da2df66b83785678420ffceadd202a17f662cb495529949337f17da84061eb508b6b05e4451d55221f42ac53a3a06c1812d50a

test:
  secret_key_base: 3e1931a59052d1aaf8655fb0690a01bf6a437cb3a5be31125952d5bf517039cbc465d389fdebd19da477b16bd4ed66adf80278cf4ec5325f6a894941fa0deae9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
